### ISSUE TITLE
One more prerequisite

### ISSUE THREAD

**Issue by qrilka** [ryantm/home-manager-template#2]
I have spent man hours last night and also some time today trying to find out why I get an error from Stack on 1 of 2 mostly the same Ubuntu machines. And I use Stack installed using HM and based on this template. It appears that I was missing `$HOME/.nix-profile/etc/profile.d/hm-session-vars.sh` in my `~/.bashrc` and a [workaround for locales](https://github.com/qrilka/home/blob/master/home.nix#L76) wasn't working correctly.
It would be useful to have this documented. Thanks.

**Comment by ryantm** [comment]
@qrilka Does this section on the Caveats saying that you need HM to manage bash not cover this? https://github.com/ryantm/home-manager-template#caveats

**Comment by qrilka** [comment]
In principle yes, thank you
See #3
