### ISSUE TITLE
CI issue - Run nix-shell - error: expected JSON string

### ISSUE THREAD

**Issue by InLaw** [ryantm/home-manager-template#4]
```
Run nix-shell
  nix-shell
  shell: /bin/bash -e {0}
error: expected JSON string
(use '--show-trace' to show detailed location information)
Error: Process completed with exit code 1.
```

![202010-04_0720_36__](https://user-images.githubusercontent.com/16096709/95007658-31d2ab00-0612-11eb-9426-e3a3ee4a41d0.png)

**Comment by ryantm** [comment]
Hmmm, I wasn't intending the github workflows to be copied via the template, I should probably remove them.

**Comment by ryantm** [comment]
I removed the .github directory to fix this.

**Comment by InLaw** [comment]
btw:

Where can I find that file "skip_adding_nixpkgs_channel"?
